### ISSUE TITLE
PathParser NoClassDefFoundException with v26.0.+ of Android support library

### ISSUE THREAD

**Issue by farhadfaghihi** [jaredrummler/AnimatedSvgView#15]
I've just upgraded my projects support library version, from 25.4.0 to 26.0.+ and the 1.0.4 version of AnimatedSvgView is throwing the following exception in my splashScreen 

```
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/graphics/drawable/PathParser;
   at java.lang.reflect.Constructor.newInstance0(Native Method)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
   at android.view.LayoutInflater.createView(LayoutInflater.java:645)
   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
   at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
   at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
   at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
   at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
   at ir.sep.sesoot.ui.splash.ActivitySplash.onCreate(ActivitySplash.java:26)
   at android.app.Activity.performCreate(Activity.java:6679)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
   at android.app.ActivityThread.-wrap12(ActivityThread.java)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:154)
   at android.app.ActivityThread.main(ActivityThread.java:6119)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.graphics.drawable.PathParser" on path: DexPathList[[zip file "/data/app/ir.sep.sesoot-2/base.apk", zip file "/data/app/ir.sep.sesoot-2/split_lib_dependencies_apk.apk", zip file "/data/app/ir.sep.sesoot-2/split_lib_slice_0_apk.apk", zip file "/data/app/ir.sep.sesoot-2/split_lib_slice_1_apk.apk", zip file "/data/app/ir.sep.sesoot-2/split_lib_slice_2_apk.apk", zip file "/data/app/ir.sep.sesoot-2/split_lib_slice_3_apk.apk", zip file "/data/app/ir.sep.sesoot-2/split_lib_slice_4_apk.apk", zip file "/data/app/ir.sep.sesoot-2/split_lib_slice_5_apk.apk", zip file "/data/app/ir.sep.sesoot-2/split_lib_slice_6_apk.apk", zip file "/data/app/ir.sep.sesoot-2/split_lib_slice_7_apk.apk", zip file "/data/app/ir.sep.sesoot-2/split_lib_slice_8_apk.apk", zip file "/data/app/ir.sep.sesoot-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/ir.sep.sesoot-2/lib/x86, /data/app/ir.sep.sesoot-2/base.apk!/lib/x86, /data/app/ir.sep.sesoot-2/split_lib_dependencies_apk.apk!/lib/x86, /data/app/ir.sep.sesoot-2/split_lib_slice_0_apk.apk!/lib/x86, /data/app/ir.sep.sesoot-2/split_lib_slice_1_apk.apk!/lib/x86, /data/app/ir.sep.sesoot-2/split_lib_slice_2_apk.apk!/lib/x86, /data/app/ir.sep.sesoot-2/split_lib_slice_3_apk.apk!/lib/x86, /data/app/ir.sep.sesoot-2/split_lib_slice_4_apk.apk!/lib/x86, /data/app/ir.sep.sesoot-2/split_lib_slice_5_apk.apk!/lib/x86, /data/app/ir.sep.sesoot-2/split_lib_slice_6_apk.apk!/lib/x86, /data/app/ir.sep.sesoot-2/split_lib_slice_7_apk.apk!/lib/x86, /data/app/ir.sep.sesoot-2/split_lib_slice_8_apk.apk!/lib/x86, /data/app/ir.sep.sesoot-2/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /vendor/lib]]
   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
   at java.lang.reflect.Constructor.newInstance0(Native Method) 
   at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
   at android.view.LayoutInflater.createView(LayoutInflater.java:645) 
   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787) 
   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) 
   at android.view.LayoutInflater.rInflate(LayoutInflater.java:858) 
   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
   at android.view.LayoutInflater.inflate(LayoutInflater.java:518) 
   at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
   at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
   at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
   at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
   at ir.sep.sesoot.ui.splash.ActivitySplash.onCreate(ActivitySplash.java:26) 
   at android.app.Activity.performCreate(Activity.java:6679) 
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
   at android.app.ActivityThread.-wrap12(ActivityThread.java) 
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
   at android.os.Handler.dispatchMessage(Handler.java:102) 
   at android.os.Looper.loop(Looper.java:154) 
   at android.app.ActivityThread.main(ActivityThread.java:6119) 
   at java.lang.reflect.Method.invoke(Native Method) 
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

**Comment by jaredrummler** [comment]
I created a new project with the `targetSdk` set to `26` and support libraries using the latest `26.0.+` and the library is working correctly. Can you please paste the `dependencies` section of your app module's `build.gradle`?

The `PathParser` looks untouched in the latest support library. Make sure to include `com.android.support:support-vector-drawable` dependency (which is already included in appcompat).

**Comment by farhadfaghihi** [comment]
I've added the support-vector-drawable dependency and now I'm having classNotFoundException on another class ( ExposedPathParser). Here comes the logcat

java.lang.NoClassDefFoundError: android.support.graphics.drawable.ExposedPathParser
                                                                 at com.jaredrummler.android.widget.AnimatedSvgView.rebuildGlyphData(AnimatedSvgView.java:267)
                                                                 at com.jaredrummler.android.widget.AnimatedSvgView.onSizeChanged(AnimatedSvgView.java:169)
                                                                 at android.view.View.sizeChange(View.java:16748)
                                                                 at android.view.View.setFrame(View.java:16710)
                                                                 at android.view.View.layout(View.java:16627)
                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                 at android.view.View.layout(View.java:16630)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                 at android.view.View.layout(View.java:16630)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                 at android.view.View.layout(View.java:16630)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                 at android.view.View.layout(View.java:16630)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                 at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                 at android.view.View.layout(View.java:16630)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                 at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                 at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
                                                                 at android.view.View.layout(View.java:16630)
                                                                 at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                 at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                 at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by farhadfaghihi** [comment]
Moreover, this is the dependencies of my app module, having the v26.0.+ of support library.

    compile dep.appcompat
    compile dep.design
    compile dep.recyclerview
    compile dep.cardview
    compile dep.animatedSvgView
    compile dep.animatedVectorDrawable
    compile dep.support_vector_drawable
    compile dep.palette
    compile dep.butterknife_core
    annotationProcessor dep.butterknife_compiler
    compile dep.pidgets
    compile dep.viewpager_transformer
    compile dep.picasso
    compile dep.onboarding
    compile dep.zxing_embedded
    compile dep.retrofit
    compile dep.retrofit_gson
    compile (dep.crashlytics) { transitive = true; }
    compile (dep.crashlytics_answers) { transitive = true ; }
    compile dep.apache_commons_lang3
    compile dep.rootbeer
    compile dep.onesignal
    compile dep.play_services_gcm
    compile dep.play_services_location
    compile dep.custom_tabs
    compile dep.support_v4

**Comment by williamdes** [comment]
gradle: 3.0.0-beta4
Same issue with :
    api 'com.android.support:appcompat-v7:27.0.2'
    api 'com.android.support:support-vector-drawable:27.0.2'
Works with : 
    api 'com.android.support:appcompat-v7:25.4.0'
    api 'com.android.support:support-vector-drawable:25.4.0'

**Comment by jaredrummler** [comment]
I was able to recreate the issue. Will work on it as soon as I get some time.

Just from quickly looking, I think the issue is that `PathParser` was moved from `android.support.graphics.drawable` to `android.support.v4.graphics`.

**Comment by jaredrummler** [comment]
Update to 1.0.5 should fix this.

**Comment by kshegde009** [comment]
I have same problem  after updating from 25 to 26 SDK level ,
and i also added this dependency 'com.android.support:support-vector-drawable:26.1.0'.
But its not working in my project ...
can u help me out ..

Error Message : 
error: cannot access PathParser
class file for android.support.graphics.drawable.PathParser not found
